// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUa8e6ULnsTws3FcSzv9Ar1-bNxTlmNOM',
    appId: '1:827245595553:web:d148fb0ffdb67908f099e0',
    messagingSenderId: '827245595553',
    projectId: 'hushin-6d8dd',
    authDomain: 'hushin-6d8dd.firebaseapp.com',
    storageBucket: 'hushin-6d8dd.firebasestorage.app',
    measurementId: 'G-PRE3N6QV31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcBcGVWBWbZI5qQ0BHfD0ZFHE92_2e5NU',
    appId: '1:827245595553:android:d78cddc8bced2a66f099e0',
    messagingSenderId: '827245595553',
    projectId: 'hushin-6d8dd',
    storageBucket: 'hushin-6d8dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0kwYDImKRRitqvQGZ4KvxlfYSasvDGq4',
    appId: '1:827245595553:ios:1b14ae133a26361bf099e0',
    messagingSenderId: '827245595553',
    projectId: 'hushin-6d8dd',
    storageBucket: 'hushin-6d8dd.firebasestorage.app',
    iosBundleId: 'com.example.hushin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0kwYDImKRRitqvQGZ4KvxlfYSasvDGq4',
    appId: '1:827245595553:ios:1b14ae133a26361bf099e0',
    messagingSenderId: '827245595553',
    projectId: 'hushin-6d8dd',
    storageBucket: 'hushin-6d8dd.firebasestorage.app',
    iosBundleId: 'com.example.hushin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUa8e6ULnsTws3FcSzv9Ar1-bNxTlmNOM',
    appId: '1:827245595553:web:e9329f3df9f4b726f099e0',
    messagingSenderId: '827245595553',
    projectId: 'hushin-6d8dd',
    authDomain: 'hushin-6d8dd.firebaseapp.com',
    storageBucket: 'hushin-6d8dd.firebasestorage.app',
    measurementId: 'G-TTB8VTYTVZ',
  );
}
